#!/usr/bin/env python3
"""Build deterministic standalone files and the package manifest, offline."""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
ASSETS = {
    'codex-termux': 'bin/codex-termux',
    'codex-termux.bash': 'completions/codex-termux.bash',
    'codex-termux.zsh': 'completions/_codex-termux',
    'codex-termux.1': 'man/codex-termux.1',
    'install.sh': 'install.sh', 'uninstall.sh': 'uninstall.sh',
    'README.md': 'README.md', 'CHANGELOG.md': 'CHANGELOG.md',
    'config.example': 'config.example', 'LICENSE': 'LICENSE', 'VERSION': 'VERSION',
}
EXECUTABLES = {'bin/codex-termux', 'install.sh', 'uninstall.sh'}


def version():
    value = (ROOT / 'VERSION').read_text(encoding='utf-8').strip()
    if not re.fullmatch(r'(0|[1-9]\d{0,7})\.(0|[1-9]\d{0,7})\.(0|[1-9]\d{0,7})', value):
        raise SystemExit('VERSION must be a stable numeric version')
    return value


def generated_files():
    release = version()
    text = (ROOT / 'src/frontend.sh').read_text(encoding='utf-8')
    for token, source in {
        '@@RUNTIME@@': 'src/runtime.cjs',
        '@@BASH_COMPLETION@@': 'completions/codex-termux.bash',
        '@@ZSH_COMPLETION@@': 'completions/_codex-termux',
    }.items():
        if text.count(token) != 1:
            raise SystemExit('missing or duplicate build marker: ' + token)
        text = text.replace(token, (ROOT / source).read_text(encoding='utf-8').rstrip('\n'))
    generated = {'bin/codex-termux': text.replace('@@VERSION@@', release).encode()}
    template = (ROOT / 'src/package.sh').read_text(encoding='utf-8')
    for name, action in [('install.sh', 'install'), ('uninstall.sh', 'uninstall')]:
        generated[name] = template.replace('@@VERSION@@', release).replace('@@ACTION@@', action).encode()
    generated['man/codex-termux.1'] = (ROOT / 'man/codex-termux.1.in').read_text(encoding='utf-8').replace('@@VERSION@@', release).encode()
    generated['PACKAGE-SHA256SUMS'] = ''.join(
        hashlib.sha256(generated[source] if source in generated else (ROOT / source).read_bytes()).hexdigest() + '  ' + name + '\n'
        for name, source in sorted(ASSETS.items())).encode()
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check generated bytes without writing files')
    options = parser.parse_args()
    generated = generated_files()
    if options.check:
        stale = [name for name, content in generated.items() if not (ROOT / name).is_file() or (ROOT / name).read_bytes() != content]
        if stale:
            raise SystemExit('Generated files are stale; run python3 tools/build.py: ' + ', '.join(stale))
        print('Generated files and package checksums match source.')
    else:
        for name, content in generated.items():
            target = ROOT / name
            target.write_bytes(content)
            target.chmod(0o755 if name in EXECUTABLES else 0o644)
        print(ROOT / 'bin/codex-termux')


if __name__ == '__main__':
    main()
